name: CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH Keys and known_hosts
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
        chmod 600 id_rsa


    - name: Connect to AWS LightSail and Run Command
      run: |
        ssh -o StrictHostKeyChecking=no -i id_rsa ubuntu@${{ secrets.LIGHTSAIL_SERVER_IP }} 'pwd'


    - name: Deploying
      run: |
        ssh -o StrictHostKeyChecking=no -i id_rsa ubuntu@${{ secrets.LIGHTSAIL_SERVER_IP }} 'bash -s' < ./deploy.sh
